INSERT INTO [UMRRecruitmentApplicant].[dbo].[Institution]
           ([InstituteName]
           ,[IsActive]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[UpdatedBy]
           ,[UpdatedDate]
		   ,[Address]
		   ,[Town]
           ,[County]
           ,[ZipCode]
           ,[CountryId]
           ,[StateId]
           ,[Telephone]
           ,[Website])

SELECT InstituteName, IsActive, CreatedBy, CreatedDate, UpdatedBy, UpdatedDate
	  ,[Address]
      ,[Town]
      ,[County]
      ,[ZipCode]
      ,[CountryId]
      ,[StateId]
      ,[Telephone]
      ,[Website] FROM [UMRRecruitementDB_New].[dbo].[Institute]