
SET IDENTITY_INSERT [UMRRecruitmentApplicant].[dbo].[Lookup_ZipCode] ON

INSERT INTO [UMRRecruitmentApplicant].[dbo].[Lookup_ZipCode]
           ([Id]
		   ,[ZipCode]
           ,[City]
           ,[StateAbbr]
           ,[County]
           ,[type]
           ,[acceptable_cities]
           ,[unacceptable_cities]
           ,[timezone]
           ,[area_codes]
           ,[latitude]
           ,[longitude]
           ,[world_region]
           ,[country]
           ,[decommissioned]
           ,[estimated_population]
           ,[notes]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[UpdatedBy]
           ,[UpdatedDate])

SELECT [Id]
      ,[ZipCode]
      ,[City]
      ,[StateAbbr]
      ,[County]
      ,[type]
      ,[acceptable_cities]
      ,[unacceptable_cities]
      ,[timezone]
      ,[area_codes]
      ,[latitude]
      ,[longitude]
      ,[world_region]
      ,[country]
      ,[decommissioned]
      ,[estimated_population]
      ,[notes]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[UpdatedBy]
      ,[UpdatedDate]
  FROM [UMRRecruitementDB_New].[dbo].[Lookup_ZipCode]